align_left_button:
  default: "Align Image Left"
  description:
    en: "Enter the text for the title of the button in the composer."
    
align_left_text:
  default: ""
  description:
    en: "Enter the placeholder text that appears in the composer after the user clicks the button."
    
align_right_button:
  default: "Align Image Right"
  description:
    en: "Enter the text for the title of the button in the composer."
    
align_right_text:
  default: ""
  description:
    en: "Enter the placeholder text that appears in the composer after the user clicks the button."
    
image_grid_button:
  default: "Image Grid"
  description:
    en: "Enter the text for the title of the button in the composer."
    
image_grid_text:
  default: "Insert uploaded images here"
  description:
    en: "Enter the placeholder text that appears in the composer after the user clicks the button."

Svg_icons: 
  type: 'list'
  list_type: 'compact'
  default: 'fa-angle-left|fa-angle-right|fa-image'
  description: 
    en: "Include FontAwesome 5 icon classes for each icon used in the list."
