align_left_button:
  default: "align image left"
  description:
    en: "Enter the text for the title of the button in the composer."
    
align_left_text:
  default: "uploaded image goes here"
  description:
    en: "Enter the placeholder text that appears in the composer after the user clicks the button."
    
align_right_button:
  default: "align image right"
  description:
    en: "Enter the text for the title of the button in the composer."
    
align_right_text:
  default: "uploaded image goes here"
  description:
    en: "Enter the placeholder text that appears in the composer after the user clicks the button."
    
image_grid_button:
  default: "make image grid"
  description:
    en: "Enter the text for the title of the button in the composer."
    
image_grid_text:
  default: "uploaded images go here"
  description:
    en: "Enter the placeholder text that appears in the composer after the user clicks the button."

Svg_icons: 
  type: 'list'
  list_type: 'compact'
  default: 'fa-angle-left|fa-angle-right|fa-compress'
  description: 
    en: "Include FontAwesome 5 icon classes for each icon used in the list."
